---
# The vars here are duplicated from Terraform `vars.tf`.
# TODO: Have a single source of truth for vars.
- name: consul server
  hosts: servers
  vars:
    datacenter: dc1
    bootstrap_expect: 3
  roles:
    - consul-server
